### PR TITLE
Added Belfast International (BFS)

### PR DESCRIPTION
**Pull request by rikbrowning**
Adding Belfast International Airport to the list of airports.

### CODE REVIEW

**Comment by lynnandtonic** [comment]
@rikbrowning Awesome! I'll get this merged soon. One question: what is that photo of?

**Comment by rikbrowning** [comment]
Picture is of the Giants Causeway, found round the north coast of Northern Ireland.

**Comment by lynnandtonic** [comment]
@rikbrowning Ah, very cool. How close is it to the airport? We'd like to have the photos show some aspect of the actual airport like architecture or artwork.

**Comment by rikbrowning** [comment]
Its about an hour away, I can try and find another picture if that suits?
On 21 Mar 2015 15:35, Lynn Fisher <notifications@github.com> wrote:@rikbrowning Ah, very cool. How close is it to the airport? We'd like to have the photos show some aspect of the actual airport like architecture or artwork.

**Comment by lynnandtonic** [comment]
That would be great, thanks! I'll take a look too. :)

**Comment by rikbrowning** [comment]
Updated image, hope it's ok.

**Comment by lynnandtonic** [comment]
I was just adding that same image. Great minds. :)

Thank you so much!

**Comment by lynnandtonic** [comment]
There we go. Thanks again!

**Pull request merged**
