### PR TITLE
+ VKO, SVX, KRR, UFA, KBP, MSQ, SVO

### PR DESCRIPTION
**Pull request by artemacis**
sorry for the wrong name for msq inst of msq.json

images are ready but didn't manage how to upload them

### CODE REVIEW

**Comment by lynnandtonic** [comment]
Thank you so much, @artemacis!

**Comment by artemacis** [comment]
@lynnandtonic you are welcome! 
Please, be so kind and change picture for LED as mentioned in my email

**Comment by lynnandtonic** [comment]
@artemacis Sorry, is the LED picture incorrect?

**Comment by artemacis** [comment]
@lynnandtonic since 2003 old Pulkovo-2 Terminal (on picture) is not in use. 
Now airport operates only in wonderful new terminal (7km away from old Pulkovo-2) and you may find dozens of nice pictures ( https://www.flickr.com/photos/korzhevdp/13228218263/in/photolist-7kq9jZ-m9Vncv-m9X193-m9W5qF-cHEfwG-7SZPEP-r5X7kx-o8Uvzw-8DVT8x-8DYRjf-c6NgEh-c6Ngio-7ePX6b-89zwbK-7eL2yz-63UPKq as example)
thnx!

**Pull request merged**
