### PR TITLE
added bdo airport (bandung,indonesia)

### PR DESCRIPTION
**Pull request by girikuncoro**
added bandung (indonesia) airport, let me know if there's any issue on this

### CODE REVIEW

**Comment by girikuncoro** [comment]
fixed bdo code

**Comment by girikuncoro** [comment]
added SUB airport (surabaya, Indonesia, 2nd busiest airport after Jakarta)

**Comment by lynnandtonic** [comment]
These photos are not Creative Commons licensed. I will take a look for some new ones.

**Comment by lynnandtonic** [comment]
@girikuncoro 

How do you feel about one of these for SUB:
https://www.flickr.com/photos/mattweibo/4735968516/in/photolist-
https://www.flickr.com/photos/123_456/8161039679
https://www.flickr.com/photos/123_456/8161037005

And for BDO:
https://www.flickr.com/photos/ikhlasulamal/8703495082/in/photolist-8bLJg2-eg6FS3-bzMbkM-dhsaWb
http://upload.wikimedia.org/wikipedia/commons/5/51/Husein_Sastranegara_Airport.jpg

We are a bit limited because of the licensing of images, but these might work. Let me know what you think!

**Comment by girikuncoro** [comment]
Sorry I didn't notice the creative commons licensed. Those look good! I'll modify the code accordingly then.

**Comment by girikuncoro** [comment]
@lynnandtonic
I changed the pictures! Please let me know if these work.

**Comment by lynnandtonic** [comment]
@girikuncoro Awesome, thank you!

**Pull request merged**
