### PR TITLE
USA Airport: SHV: Shreveport Regional Airport

### PR DESCRIPTION
**Pull request by patilchetan**
@lynnandtonic:

Added an USA airport: [Shreveport Regional Airport.](http://en.wikipedia.org/wiki/Shreveport_Regional_Airport)

Refer: https://github.com/lynnandtonic/airport-codes/issues/354

### CODE REVIEW

**Comment by patilchetan** [comment]
@lynnandtonic, with same pull request:

Added an USA airport: [Shreveport Downtown Airport.](http://en.wikipedia.org/wiki/Shreveport_Downtown_Airport)

Refer: https://github.com/lynnandtonic/airport-codes/issues/354

**Comment by patilchetan** [comment]
@lynnandtonic, with same pull request:

Added an USA airport: [San Antonio International Airport.](http://en.wikipedia.org/wiki/San_Antonio_International_Airport)

Refer: https://github.com/lynnandtonic/airport-codes/issues/353

**Comment by patilchetan** [comment]
@lynnandtonic, with same pull request:

Added an USA airport: [Stinson Municipal Airport.](http://en.wikipedia.org/wiki/Stinson_Municipal_Airport)

Refer: https://github.com/lynnandtonic/airport-codes/issues/353

**Comment by patilchetan** [comment]
@lynnandtonic, with same pull request:

Added an USA airport: [Lehigh Valley International Airport.](http://en.wikipedia.org/wiki/Lehigh_Valley_International_Airport)

Refer: https://github.com/lynnandtonic/airport-codes/issues/352

**Comment by lynnandtonic** [comment]
Thank you!

**Pull request merged**
