### PR TITLE
Adding KIR and CFN

### PR DESCRIPTION
**Pull request by computerfan0**
Adding KIR (Kerry Airport) and CFN (Donegal Airport). This will close issue #1279. A few notes:

1. I was unsure about what city to add for these airports as they both serve counties as opposed to towns or cities. In both these cases, I added the locations of the airports themselves (Farranfore and Carrickfinn respectively) as the city, with the county being added to city2. I did this as both of these airports are frequently referred to Farranfore Airport and Carrickfinn Airport respectively and neither markets themselves as serving any specific town. (There is a town named Donegal but it is rather far from the airport)
2. Donegal Airport's name is in Irish as it is in the Gaeltacht (an Irish speaking region of Ireland).

Again, tell me if there's anything I've missed.

### CODE REVIEW

**Comment by computerfan0** [comment]
Also, am I allowed to use a Creative Commons NoDerivatives licensed photo? I have found a better photo but it is under a NoDerivatives license.

**Comment by lynnandtonic** [comment]
@computerfan0 Yes Creative Commons NoDerivatives should be fine!

**Comment by computerfan0** [comment]
> @computerfan0 Yes Creative Commons NoDerivatives should be fine!

**Comment by computerfan0** [comment]
> @computerfan0 Yes Creative Commons NoDerivatives should be fine!

Replaced the image than!
(I accidentally clicked "close pull request" while typing the comment)

**Comment by lynnandtonic** [comment]
Beautiful! Thank you so much! 💯

**Pull request merged**
