### PR TITLE
USA Airport: SUN: Friedman Memorial Airport

### PR DESCRIPTION
**Pull request by patilchetan**
Added an USA airport: [Friedman Memorial Airport.]
(http://en.wikipedia.org/wiki/Friedman_Memorial_Airport)

Refer: https://github.com/lynnandtonic/airport-codes/issues/249

### CODE REVIEW

**Comment by patilchetan** [comment]
With same pull request: 

Added an USA airport: [McGhee Tyson Airport.]
(http://en.wikipedia.org/wiki/McGhee_Tyson_Airport)

Refer: https://github.com/lynnandtonic/airport-codes/issues/174

**Comment by patilchetan** [comment]
With same pull request: 

Added an USA airport: [Tri-Cities Regional Airport.]
(http://en.wikipedia.org/wiki/Tri-Cities_Regional_Airport)

Refer: https://github.com/lynnandtonic/airport-codes/issues/237

**Comment by patilchetan** [comment]
With same pull request: 

Added an USA airport: [Fort Wayne International Airport.]
(http://en.wikipedia.org/wiki/Fort_Wayne_International_Airport)

Refer: https://github.com/lynnandtonic/airport-codes/issues/273

**Comment by lynnandtonic** [comment]
Thank you!

**Pull request merged**
