### PR TITLE
Revert 1 patch 1

### PR DESCRIPTION
**Pull request by ondrew**

### CODE REVIEW

**Comment by ondrew** [comment]
Lynn - I have all content prepared but I hardly understand github :)
(bts.json & al limages)

**Comment by lynnandtonic** [comment]
No problem, @ondrew. I can take care of the merge soon. Thank you so much! :)

**Comment by lynnandtonic** [comment]
@ondrew, unfortunately the photo you chose is copyrighted so we won't be able to use it. I'll find another one that will work. :)

**Comment by ondrew** [comment]
@lynnandtonic I changed copyright to CC for this picture on Flickr. it should be OK now. Please use this  picture if possible. Thanks. BTW great ideam & work.

**Pull request merged**
