### PR TITLE
Add *Ros*ario International Aiport - Argentina

### PR DESCRIPTION
**Pull request by p4bl1t0**
Description + CC images

### CODE REVIEW

**Comment by lynnandtonic** [comment]
Thank you, @p4bl1t0! What do you think about using this image instead? https://www.flickr.com/photos/lu6fpj/2753453510

**Comment by p4bl1t0** [comment]
You're welcome @lynnandtonic! When I searhed I did not find that image. I think it's a nice picture. Do you want me to update it?

**Comment by lynnandtonic** [comment]
Sure, if you don't mind. I can too, if you'd prefer. :)

**Comment by lynnandtonic** [comment]
@p4bl1t0, I'm going to merge this and I'll update the photo. :)

**Comment by lynnandtonic** [comment]
Thank you!

**Comment by p4bl1t0** [comment]
Than you! My work doesn't allow me to update it sooner

**Pull request merged**
