### PR TITLE
Updating dependencies to work with node 7

### PR DESCRIPTION
**Pull request by jasonrose**
Can you clone this repo and see if it lets you `npm run dev` and `npm run build` again?

### CODE REVIEW

**Comment by lynnandtonic** [comment]
@jasonrose So this eliminates the error I was getting and it seems like it runs ok, but when I go to preview it in the browser I get a `Cannot GET /` message. Any ideas there?

**Comment by jasonrose** [comment]
Not sure, I'll look into it some more

**Comment by jasonrose** [comment]
I think I figured it out.  Pull this and npm install again.

**Comment by lynnandtonic** [comment]
@jasonrose It works! Going to merge. Thank you so so so much. 😻

**Pull request merged**
