### PR TITLE
Programmatically generating card/small/medium photos from the large original

### PR DESCRIPTION
**Pull request by jasonrose**
I did some similar work in https://github.com/lynnandtonic/airport-codes/pull/967 but I'm closing that in lieu of this.

The summary of this PR is that we can automate the generation of the different sizes for each photo that we want on the site.  This accomplishes a few goals:
1. reduces the burden on contributors so that they only have to provide the `large` size
2. makes size alterations for specific sizes much easier (e.g., this PR also changes the `card` height from 250px to 220px)
3. lets us make tradeoffs on image quality, load time, size, etc in a holistic and consistent manner

For specific metrics, this PR has the following impact:

Loading the index on my 1920x1200 monitor

| Configuration | Initial Image Load Size (Bytes) |
| ------------- | ------------------------------- |
| Before | 1.1MB |
| After | 470KB |

The net result is an upper bounds of 600KB savings on initial page load.  Each `card` is 10-30KB smaller.

In terms of overall size, these is the comparison of the image directories on disk:

| Directory | Before | After |
| ------------ | --------: | ------: |
| `assets/images/small` | 64M	| 36M |
| `assets/images/large` | 242M | 242M |
| `assets/images/medium` | 132M | 96M |
| `assets/images/card` | 38M | 17M |
| `assets/images` | 478M | 394M |

### CODE REVIEW

**Comment by lynnandtonic** [comment]
Thank you @jasonrose! This is awesome! 🌈 

Having the card image size at 220px makes them look a bit fuzzy on retina, but going to take a closer look later today and see if that's a huge deal.

**Comment by jasonrose** [comment]
It might also be jpeg downsampling instead of browser scaling.  You can change https://github.com/lynnandtonic/airport-codes/blob/bc47d4f467c60d6535b9751efc24764eb1069d97/sharp.js#L16 to be `.jpeg({quality: 90})` to try with a higher quality.  The plugin defaults to `80`. (https://sharp.dimens.io/en/stable/api-output/#jpeg).

If it still looks blurry in retina, it might be worth generating retina cards and using a media query for them.  What's the traffic breakdown on retina vs non retina?

**Comment by lynnandtonic** [comment]
I don't think GA tracks pixel density but a vast majority are Windows users. Then a far second is iOS.

I was trying to run the `./sharp.js` command but got an `UnhandledPromiseRejectionWarning` error. Any ideas?

**Comment by jasonrose** [comment]
Can you copy and paste the output?  I've seen that warning in other contexts and it's been ignorable.

**Comment by lynnandtonic** [comment]
```
👉  ./sharp.js
processing /Users/lfisher/git/airport-codes/assets/images/card/.DS_Store
processing /Users/lfisher/git/airport-codes/assets/images/medium/.DS_Store
processing /Users/lfisher/git/airport-codes/assets/images/small/.DS_Store
(node:93082) UnhandledPromiseRejectionWarning: Error: Input file is missing or of an unsupported image format
(node:93082) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:93082) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jasonrose** [comment]
Ok thanks.  I'll update the script to only load images.  It failed because it tried to parse those OSX `.DS_Store` files.  Sorry for the inconvenience.

**Comment by lynnandtonic** [comment]
@jasonrose Is there a way to run Sharp on only a new image that's added? Or does `./sharp.js` always run all the images?

**Comment by jasonrose** [comment]
It currently runs it on everything in the `images/large` directory.  I can make it take files as arguments as well.

**Comment by lynnandtonic** [comment]
@jasonrose Cool! I think if we have a command that people can run just for their new images, I'll be good to merge this. THANK YOU! 🌈

**Comment by jasonrose** [comment]
A user can now run `./sharp.js` to update every image or `./sharp.js assets/images/large/a*` or any other shell expansion to give a list of files to update.

**Comment by lynnandtonic** [comment]
Thank you so much @jasonrose! You're the best! 💚💚💚💚

**Pull request merged**
